binance:
  timeframes:
  - 1h
  - 4h
  - 1d
  symbols:
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - SOLUSDT
  - XRPUSDT
  - ZECUSDT
  - UNIUSDT
  - DOGEUSDT
  - SUIUSDT
  - ENAUSDT
  - UUSDT
  - HEMIUSDT
  - NEARUSDT
  - TRXUSDT
  - LINKUSDT
  - FILUSDT
  - TRUMPUSDT
  - ARBUSDT
  - AAVEUSDT
  - SNDKBUSDT
  - ACEUSDT
  - PUMPUSDT
  - ADAUSDT
  - PEPEUSDT
  - LTCUSDT
  - BMTUSDT
  - WLDUSDT
  - TUSDT
  - AVAXUSDT
  - TUTUSDT
  - PROMUSDT
  - TAOUSDT
  - CRCLBUSDT
  - CRVUSDT
  - ASTERUSDT
  - XPLUSDT
  - CHIPUSDT
  - XLMUSDT
  - ENSOUSDT
  - MSTRBUSDT
  - FFUSDT
  - GRAMUSDT
  - DASHUSDT
  - ICPUSDT
  - ONGUSDT
  - SOXLBUSDT
  - DOTUSDT
  - APTUSDT
  - ONDOUSDT
  - OPUSDT
  - LAUSDT
  - FETUSDT
  - PENGUUSDT
  - SPCXBUSDT
  - INJUSDT
  - PYTHUSDT
  - ROBOUSDT
  - ETHFIUSDT
  - 0GUSDT
  - BCHUSDT
  - HBARUSDT
  - MUBARAKUSDT
  - JSTUSDT
  - VIRTUALUSDT
  - SNXXBUSDT
  - PENDLEUSDT
  - SCUSDT
  - KITEUSDT
  - WLFIUSDT
  - MORPHOUSDT
  - MUBUSDT
  - METABUSDT
  - ARUSDT
  - SEIUSDT
  - HOMEUSDT
  - ZROUSDT
  - POLUSDT
  - TIAUSDT
  - MITOUSDT
  - SOPHUSDT
  - ZKCUSDT
  - BICOUSDT
  - CAKEUSDT
  - DEXEUSDT
  - ENSUSDT
  - TLMUSDT
  - GIGGLEUSDT
  - SKHYBUSDT
  - SHIBUSDT
  - MIRAUSDT
  - ZKPUSDT
  - QQQBUSDT
  - LDOUSDT
  - BONKUSDT
  - RENDERUSDT
  - ZENUSDT
  - HEIUSDT
  - WBTCUSDT
  - RUNEUSDT
  - KORUBUSDT
  - EGLDUSDT
  - NVDABUSDT
  - TWTUSDT
  - PLUMEUSDT
  - GPSUSDT
  - SANDUSDT
  - CFGUSDT
  - JTOUSDT
us_stocks:
  provider: yahoo
  timeframes:
  - 1h
  - 1d
  symbols:
  - AAPL
  - MSFT
  - NVDA
  - AMZN
  - GOOGL
bist:
  provider: yahoo
  timeframes:
  - 1d
  symbols:
  - THYAO.IS
  - ASELS.IS
  - GARAN.IS
  - SISE.IS
  - KCHOL.IS
backtest_defaults:
  initial_capital: 10000
  fee_bps: 10
  slippage_bps: 5
  start: '2021-01-01'
